// This file is auto-generated by scripts/generate-rbac-from-canon.sh
// Source of truth: docs/validation/rbac-canon-v1.json
// Canon version: v1

pub const ALL_CAPABILITIES: &[&str] = &[
    "analytics.kpis.read",
    "audit.events.read",
    "billing.balance.read",
    "billing.close_cash.write",
    "billing.invoice.read",
    "billing.invoices.read",
    "bookings.checkout.override",
    "bookings.extra_charges.read",
    "bookings.extra_charges.write",
    "bookings.read",
    "bookings.update",
    "bookings.write",
    "guests.read",
    "guests.write",
    "housekeeping.read",
    "housekeeping.write",
    "reports.occupancy.read",
    "reports.revenue.read",
    "rooms.read",
    "rooms.search",
    "rooms.status.write",
    "rooms.write",
    "saas.hotels.read",
    "saas.hotels.write",
    "users.delete",
    "users.read",
    "users.write",
];

pub const ADMIN_CAPABILITIES: &[&str] = &[
    "rooms.read",
    "rooms.write",
    "rooms.search",
    "rooms.status.write",
    "bookings.read",
    "bookings.write",
    "bookings.update",
    "bookings.checkout.override",
    "bookings.extra_charges.read",
    "bookings.extra_charges.write",
    "guests.read",
    "guests.write",
    "housekeeping.read",
    "housekeeping.write",
    "billing.balance.read",
    "billing.close_cash.write",
    "billing.invoices.read",
    "billing.invoice.read",
    "analytics.kpis.read",
    "audit.events.read",
    "reports.revenue.read",
    "reports.occupancy.read",
    "users.read",
    "users.write",
    "users.delete",
];

pub const SAAS_ADMIN_CAPABILITIES: &[&str] = &["saas.hotels.read", "saas.hotels.write"];

pub const OPS_CAPABILITIES: &[&str] = &[
    "rooms.read",
    "rooms.search",
    "rooms.status.write",
    "bookings.read",
    "bookings.write",
    "bookings.update",
    "bookings.extra_charges.read",
    "bookings.extra_charges.write",
    "guests.read",
    "guests.write",
    "housekeeping.read",
    "housekeeping.write",
    "billing.balance.read",
    "billing.close_cash.write",
    "billing.invoices.read",
    "billing.invoice.read",
    "analytics.kpis.read",
    "audit.events.read",
    "reports.revenue.read",
    "reports.occupancy.read",
];

pub const RECEPTIONIST_CAPABILITIES: &[&str] = &[
    "rooms.read",
    "rooms.search",
    "bookings.read",
    "bookings.write",
    "bookings.update",
    "bookings.extra_charges.read",
    "bookings.extra_charges.write",
    "guests.read",
    "guests.write",
    "billing.balance.read",
    "billing.invoice.read",
];

pub const HOUSEKEEPING_CAPABILITIES: &[&str] = &["housekeeping.read", "housekeeping.write"];

#[inline]
fn has_capability(capabilities: &[&str], capability: &str) -> bool {
    capabilities.contains(&capability)
}

pub fn role_has_capability(role: &str, capability: &str) -> bool {
    match role {
        "admin" => has_capability(ADMIN_CAPABILITIES, capability),
        "saas_admin" => has_capability(SAAS_ADMIN_CAPABILITIES, capability),
        "ops" => has_capability(OPS_CAPABILITIES, capability),
        "receptionist" => has_capability(RECEPTIONIST_CAPABILITIES, capability),
        "housekeeping" => has_capability(HOUSEKEEPING_CAPABILITIES, capability),
        _ => false,
    }
}
