#!/usr/bin/env bash
set -euo pipefail

if [ ! -f "backend/Cargo.toml" ]; then
  echo "Run from repo root." >&2
  exit 1
fi

./scripts/generate-rbac-from-canon.sh --check

BACKEND_RBAC_FILE="backend/src/infrastructure/web/middleware/rbac.rs"
BACKEND_GENERATED_FILE="backend/src/infrastructure/web/middleware/rbac_generated.rs"
FRONTEND_CAPS_FILE="frontend/src/features/auth/capabilities.ts"

if ! grep -Fq "auto-generated by scripts/generate-rbac-from-canon.sh" "$BACKEND_GENERATED_FILE"; then
  echo "RBAC canon check: FAIL ($BACKEND_GENERATED_FILE is not generated from canon)" >&2
  exit 1
fi

if ! grep -Fq "auto-generated by scripts/generate-rbac-from-canon.sh" "$FRONTEND_CAPS_FILE"; then
  echo "RBAC canon check: FAIL ($FRONTEND_CAPS_FILE is not generated from canon)" >&2
  exit 1
fi

if ! grep -Fq "rbac_generated::role_has_capability" "$BACKEND_RBAC_FILE"; then
  echo "RBAC canon check: FAIL ($BACKEND_RBAC_FILE must delegate to rbac_generated)" >&2
  exit 1
fi

if grep -Eq "pub const [A-Z_]+_CAPABILITIES" "$BACKEND_RBAC_FILE"; then
  echo "RBAC canon check: FAIL (manual capability matrix found in $BACKEND_RBAC_FILE)" >&2
  exit 1
fi

if grep -Eq "const [A-Z_]+_CAPABILITIES" "$FRONTEND_CAPS_FILE"; then
  :
fi

if grep -RIn --exclude='rbac_generated.rs' --exclude='capabilities.ts' -E "ROLE_CAPABILITIES|[A-Z_]+_CAPABILITIES" backend/src frontend/src >/tmp/hms_rbac_manual_matrix_hits.txt; then
  echo "RBAC canon check: FAIL (manual RBAC matrix outside canon-generated files):" >&2
  cat /tmp/hms_rbac_manual_matrix_hits.txt >&2
  rm -f /tmp/hms_rbac_manual_matrix_hits.txt
  exit 1
fi
rm -f /tmp/hms_rbac_manual_matrix_hits.txt

echo "RBAC canon check: PASS"
