#!/usr/bin/env bash
set -euo pipefail

if [ ! -f "backend/Cargo.toml" ]; then
  echo "Run from repo root." >&2
  exit 1
fi

MODE="write"
if [[ "${1:-}" == "--check" ]]; then
  MODE="check"
elif [[ -n "${1:-}" ]]; then
  echo "Usage: $0 [--check]" >&2
  exit 1
fi

CANON_FILE="docs/validation/rbac-canon-v1.json"
TXT_OUT="docs/validation/rbac-canon-v1.txt"
BACKEND_OUT="backend/src/infrastructure/web/middleware/rbac_generated.rs"
FRONTEND_OUT="frontend/src/features/auth/capabilities.ts"

python3 - "$MODE" "$CANON_FILE" "$TXT_OUT" "$BACKEND_OUT" "$FRONTEND_OUT" <<'PY'
from __future__ import annotations

import json
import sys
from pathlib import Path

mode, canon_path, txt_out, backend_out, frontend_out = sys.argv[1:]


def read_canon(path: Path) -> dict:
    if not path.exists():
        raise SystemExit(f"Missing canon file: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    required_keys = {"version", "roles", "capabilities", "role_capabilities"}
    missing = required_keys - data.keys()
    if missing:
        raise SystemExit(f"Canon missing keys: {', '.join(sorted(missing))}")
    return data


def validate_canon(data: dict) -> tuple[list[str], list[str], dict[str, list[str]]]:
    roles = data["roles"]
    capabilities = data["capabilities"]
    role_caps = data["role_capabilities"]

    if not isinstance(roles, list) or not roles:
        raise SystemExit("roles must be a non-empty list")
    if len(set(roles)) != len(roles):
        raise SystemExit("roles contains duplicates")
    if not isinstance(capabilities, list) or not capabilities:
        raise SystemExit("capabilities must be a non-empty list")
    if len(set(capabilities)) != len(capabilities):
        raise SystemExit("capabilities contains duplicates")

    canon_set = set(capabilities)
    for role in roles:
        if role not in role_caps:
            raise SystemExit(f"role_capabilities missing role: {role}")
        caps = role_caps[role]
        if not isinstance(caps, list):
            raise SystemExit(f"role_capabilities[{role}] must be a list")
        if len(set(caps)) != len(caps):
            raise SystemExit(f"role_capabilities[{role}] contains duplicates")
        unknown = sorted(set(caps) - canon_set)
        if unknown:
            raise SystemExit(
                f"role_capabilities[{role}] has unknown capabilities: {', '.join(unknown)}"
            )

    return roles, sorted(capabilities), {role: role_caps[role] for role in roles}


def role_const_name(role: str) -> str:
    return f"{role.upper()}_CAPABILITIES"


def render_capability_list(caps: list[str], indent: str) -> str:
    lines = [f'{indent}"{cap}",' for cap in caps]
    return "\n".join(lines)


def render_rust_array(name: str, caps: list[str]) -> list[str]:
    if len(caps) <= 2:
        values = ", ".join(f'"{cap}"' for cap in caps)
        return [f"pub const {name}: &[&str] = &[{values}];", ""]
    return [
        f"pub const {name}: &[&str] = &[",
        render_capability_list(caps, "    "),
        "];",
        "",
    ]


def render_backend(version: str, roles: list[str], all_caps: list[str], role_caps: dict[str, list[str]]) -> str:
    lines: list[str] = []
    lines.append("// This file is auto-generated by scripts/generate-rbac-from-canon.sh")
    lines.append("// Source of truth: docs/validation/rbac-canon-v1.json")
    lines.append(f"// Canon version: {version}")
    lines.append("")
    lines.append("pub const ALL_CAPABILITIES: &[&str] = &[")
    lines.append(render_capability_list(all_caps, "    "))
    lines.append("];")
    lines.append("")
    for role in roles:
        const_name = role_const_name(role)
        lines.extend(render_rust_array(const_name, role_caps[role]))
    lines.append("#[inline]")
    lines.append("fn has_capability(capabilities: &[&str], capability: &str) -> bool {")
    lines.append("    capabilities.contains(&capability)")
    lines.append("}")
    lines.append("")
    lines.append("pub fn role_has_capability(role: &str, capability: &str) -> bool {")
    lines.append("    match role {")
    for role in roles:
        const_name = role_const_name(role)
        lines.append(f'        "{role}" => has_capability({const_name}, capability),')
    lines.append("        _ => false,")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_frontend(version: str, roles: list[str], all_caps: list[str], role_caps: dict[str, list[str]]) -> str:
    lines: list[str] = []
    lines.append("// This file is auto-generated by scripts/generate-rbac-from-canon.sh")
    lines.append("// Source of truth: docs/validation/rbac-canon-v1.json")
    lines.append(f"// Canon version: {version}")
    lines.append("")
    lines.append('import { UserRole } from "@/types/domain";')
    lines.append("")
    lines.append("export type Capability =")
    for i, cap in enumerate(all_caps):
        suffix = ";" if i == len(all_caps) - 1 else ""
        lines.append(f'  | "{cap}"{suffix}')
    lines.append("")
    for role in roles:
        const_name = role_const_name(role)
        lines.append(f"const {const_name}: readonly Capability[] = [")
        lines.append(render_capability_list(role_caps[role], "  "))
        lines.append("];")
        lines.append("")
    lines.append("const ROLE_CAPABILITIES: Record<UserRole, readonly Capability[]> = {")
    for role in roles:
        const_name = role_const_name(role)
        lines.append(f"  {role}: {const_name},")
    lines.append("};")
    lines.append("")
    lines.append("export const roleHasCapability = (")
    lines.append("  role: UserRole | string | undefined,")
    lines.append("  capability: Capability,")
    lines.append("): boolean => {")
    lines.append("  if (!role) return false;")
    lines.append("  const capabilities = ROLE_CAPABILITIES[role as UserRole];")
    lines.append("  if (!capabilities) return false;")
    lines.append("  return capabilities.includes(capability);")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def render_txt(all_caps: list[str]) -> str:
    return "\n".join(all_caps) + "\n"


def write_or_check(path: Path, content: str, check: bool, mismatches: list[str]) -> None:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            mismatches.append(str(path))
        return
    path.write_text(content, encoding="utf-8")


canon = read_canon(Path(canon_path))
roles, all_caps, role_caps = validate_canon(canon)

backend_content = render_backend(canon["version"], roles, all_caps, role_caps)
frontend_content = render_frontend(canon["version"], roles, all_caps, role_caps)
txt_content = render_txt(all_caps)

mismatches: list[str] = []
check_mode = mode == "check"
write_or_check(Path(txt_out), txt_content, check_mode, mismatches)
write_or_check(Path(backend_out), backend_content, check_mode, mismatches)
write_or_check(Path(frontend_out), frontend_content, check_mode, mismatches)

if check_mode and mismatches:
    print("RBAC generation drift detected in:", file=sys.stderr)
    for file in mismatches:
        print(f"  - {file}", file=sys.stderr)
    raise SystemExit(1)

print("RBAC generation check: PASS" if check_mode else "RBAC generation: updated files")
PY
